# Generated by Django 3.0.3 on 2020-07-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BANK', models.CharField(max_length=50)),
                ('IFSC', models.CharField(max_length=12)),
                ('CENTRE', models.CharField(max_length=50)),
                ('DISTRICT', models.CharField(max_length=50)),
                ('STATE', models.CharField(max_length=50)),
                ('ADDRESS', models.CharField(max_length=1000)),
                ('CONTACT', models.CharField(max_length=15)),
                ('IMPS', models.CharField(max_length=6, null=True)),
                ('RTGS', models.CharField(max_length=6, null=True)),
                ('CITY', models.CharField(max_length=50)),
                ('NEFT', models.CharField(max_length=6, null=True)),
                ('MICR', models.CharField(max_length=18, null=True)),
                ('UPI', models.CharField(max_length=6, null=True)),
            ],
        ),
    ]
